MCU_SERIES = f4
CMSIS_MCU = STM32F407xx
AF_FILE = boards/COLUMBUS/stm32f407_af.csv
LD_FILES = boards/COLUMBUS/columbus.ld boards/COLUMBUS/common_ifs.ld
TEXT0_ADDR = 0x08000000
TEXT1_ADDR = 0x08020000
# MicroPython settings
MICROPY_PY_LWIP = 1
MICROPY_PY_SSL = 1
MICROPY_SSL_MBEDTLS = 1
MICROPY_PY_SOCKET = 1

FROZEN_MANIFEST = $(BOARD_DIR)/manifest.py
#01studio
MICROPY_PY_PICLIB = 1
MICROPY_PY_VIDEO  = 1
MICROPY_PY_MP3	  = 1
